// <auto-generated />
using System;
using DormInfrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DormInfrastructure.Migrations
{
    [DbContext(typeof(DbDormContext))]
    partial class DbDormContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DormDomain.Model.Accommodation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pr_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("KiId")
                        .HasColumnType("integer")
                        .HasColumnName("ki_id");

                    b.Property<DateOnly?>("PrDataVysel")
                        .HasColumnType("date")
                        .HasColumnName("pr_data_vysel");

                    b.Property<DateOnly>("PrDataZasel")
                        .HasColumnType("date")
                        .HasColumnName("pr_data_zasel");

                    b.Property<int>("StId")
                        .HasColumnType("integer")
                        .HasColumnName("st_id");

                    b.HasKey("Id")
                        .HasName("accommodation_pkey");

                    b.HasIndex(new[] { "KiId" }, "idx_accommodation_ki_id");

                    b.HasIndex(new[] { "StId" }, "idx_accommodation_st_id");

                    b.ToTable("accommodation", (string)null);
                });

            modelBuilder.Entity("DormDomain.Model.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ka_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FaId")
                        .HasColumnType("integer")
                        .HasColumnName("fa_id");

                    b.Property<string>("KaInformation")
                        .HasColumnType("text")
                        .HasColumnName("ka_information");

                    b.Property<string>("KaName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ka_name");

                    b.Property<string>("KaTelefon")
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("ka_telefon");

                    b.Property<string>("KaZaviduvach")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ka_zaviduvach");

                    b.HasKey("Id")
                        .HasName("department_pkey");

                    b.HasIndex(new[] { "FaId" }, "idx_department_fa_id");

                    b.ToTable("department", (string)null);
                });

            modelBuilder.Entity("DormDomain.Model.Dorm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("gu_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GuAdresa")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("gu_adresa");

                    b.Property<string>("GuInformation")
                        .HasColumnType("text")
                        .HasColumnName("gu_information");

                    b.Property<int?>("GuKilkistPoverh")
                        .HasColumnType("integer")
                        .HasColumnName("gu_kilkist_poverh");

                    b.Property<string>("GuKomendant")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("gu_komendant");

                    b.Property<string>("GuNomer")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("gu_nomer");

                    b.HasKey("Id")
                        .HasName("dorm_pkey");

                    b.ToTable("dorm", (string)null);
                });

            modelBuilder.Entity("DormDomain.Model.Faculty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("fa_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FaDekan")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("fa_dekan");

                    b.Property<string>("FaInformation")
                        .HasColumnType("text")
                        .HasColumnName("fa_information");

                    b.Property<string>("FaKorpus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("fa_korpus");

                    b.Property<string>("FaName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("fa_name");

                    b.Property<string>("FaTelefon")
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("fa_telefon");

                    b.HasKey("Id")
                        .HasName("faculty_pkey");

                    b.ToTable("faculty", (string)null);
                });

            modelBuilder.Entity("DormDomain.Model.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ki_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GuId")
                        .HasColumnType("integer")
                        .HasColumnName("gu_id");

                    b.Property<string>("KiInformation")
                        .HasColumnType("text")
                        .HasColumnName("ki_information");

                    b.Property<int?>("KiMistkist")
                        .HasColumnType("integer")
                        .HasColumnName("ki_mistkist");

                    b.Property<string>("KiNomer")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("ki_nomer");

                    b.Property<int?>("KiPoverh")
                        .HasColumnType("integer")
                        .HasColumnName("ki_poverh");

                    b.HasKey("Id")
                        .HasName("room_pkey");

                    b.HasIndex(new[] { "GuId" }, "idx_room_gu_id");

                    b.ToTable("room", (string)null);
                });

            modelBuilder.Entity("DormDomain.Model.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("st_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FaId")
                        .HasColumnType("integer")
                        .HasColumnName("fa_id");

                    b.Property<int>("KaId")
                        .HasColumnType("integer")
                        .HasColumnName("ka_id");

                    b.Property<DateOnly?>("StDataNarodz")
                        .HasColumnType("date")
                        .HasColumnName("st_data_narodz");

                    b.Property<int?>("StKurs")
                        .HasColumnType("integer")
                        .HasColumnName("st_kurs");

                    b.Property<string>("StPib")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("st_pib");

                    b.Property<string>("StTelefon")
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("st_telefon");

                    b.HasKey("Id")
                        .HasName("student_pkey");

                    b.HasIndex(new[] { "FaId" }, "idx_student_fa_id");

                    b.HasIndex(new[] { "KaId" }, "idx_student_ka_id");

                    b.ToTable("student", (string)null);
                });

            modelBuilder.Entity("DormInfrastructure.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<int?>("StudentId")
                        .HasColumnType("integer");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DormDomain.Model.Accommodation", b =>
                {
                    b.HasOne("DormDomain.Model.Room", "Ki")
                        .WithMany("Accommodations")
                        .HasForeignKey("KiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("accommodation_ki_id_fkey");

                    b.HasOne("DormDomain.Model.Student", "St")
                        .WithMany("Accommodations")
                        .HasForeignKey("StId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("accommodation_st_id_fkey");

                    b.Navigation("Ki");

                    b.Navigation("St");
                });

            modelBuilder.Entity("DormDomain.Model.Department", b =>
                {
                    b.HasOne("DormDomain.Model.Faculty", "Fa")
                        .WithMany("Departments")
                        .HasForeignKey("FaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("department_fa_id_fkey");

                    b.Navigation("Fa");
                });

            modelBuilder.Entity("DormDomain.Model.Room", b =>
                {
                    b.HasOne("DormDomain.Model.Dorm", "Gu")
                        .WithMany("Rooms")
                        .HasForeignKey("GuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("room_gu_id_fkey");

                    b.Navigation("Gu");
                });

            modelBuilder.Entity("DormDomain.Model.Student", b =>
                {
                    b.HasOne("DormDomain.Model.Faculty", "Fa")
                        .WithMany("Students")
                        .HasForeignKey("FaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("student_fa_id_fkey");

                    b.HasOne("DormDomain.Model.Department", "Ka")
                        .WithMany("Students")
                        .HasForeignKey("KaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("student_ka_id_fkey");

                    b.Navigation("Fa");

                    b.Navigation("Ka");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DormInfrastructure.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DormInfrastructure.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DormInfrastructure.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DormInfrastructure.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DormDomain.Model.Department", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("DormDomain.Model.Dorm", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("DormDomain.Model.Faculty", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("DormDomain.Model.Room", b =>
                {
                    b.Navigation("Accommodations");
                });

            modelBuilder.Entity("DormDomain.Model.Student", b =>
                {
                    b.Navigation("Accommodations");
                });
#pragma warning restore 612, 618
        }
    }
}
